df<-data.frame(irum=c("조정순","한민애","고승민"),age=c(43,27,33))
df
irum<-c("조정순","한민애","고승민")
age<-c(43,27,33)
df2<-data.frame(이름=irum,나이=age)
df2
df2$이름
df2$나이+1
carinfo<-matrix(c('11km','13km','15km','h사','p사','r사'),ncol=2)
carinfo
dfr<-as.data.frame(carinfo)
dfr
names(dfr)<-c("연비","제조사")
dfr
pinfo<-read.table("d:\\r1\\personal.txt",header=TRUE)
pinfo
pjobinfo<-read.table("d:\\r1\\pjob.txt",header=TRUE)
pjobinfo
lifeinfo<-data.frame(취미=c("목공예","패러글라이딩","등산","꽃꽃이","독서"),
관심분야=c("취업","아파트분양","주택대출","이직","교통인프라"))
lifeinfo
myinfo<-cbind(pinfo,lifeinfo)
myinfo

otherinfo<-data.frame(이름=c("황성주","윤준영"),거주지역=c("강원","충북"),나이=c(42,45),
성별=c("여","여"))
otherinfo
totinfo<-rbind(pinfo,otherinfo)
totinfo
coremember<-merge(pinfo,pjobinfo)
coremember
merge(pinfo,pjobinfo,all=TRUE)
data1<-subset(pinfo,select=-거주지역)
data1
data<-subset(pinfo,select=c(이름,나이))
data
data2<-cbind(pinfo,결혼=c(FALSE,TRUE,TRUE,FALSE,TRUE))
data2
data2<-data2[-3,]
data2<-data2[,-5]
ncol(data2)
nrow(data2)
colnames(data2)<-c("성명","거주지","나이","성별")
names(data2)
